[package]
name = "brc_stackyak"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
memmap2 = "0.9.5"
rustc-hash = "2.0.0"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
