[package]
name = "brc_stackyak"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
memchr = "2.7.4"
memmap2 = "0.9.5"
rayon = "1.10.0"
rustc-hash = "2.0.0"
